### ISSUE TITLE
文档说明如何自定义录入组件

### ISSUE THREAD

**Issue by a30f49** [kequandian/zero-element-docs#12]
包括变更输入框焦点边框颜色， 各类自定义录入组件

**Comment by youyeke** [comment]
如果想要保持原有的组件只改变样式, 参考 #7
如果想要彻底自定义, 那就自己编写相关组件, 然后 [参考](https://github.com/kequandian/zero-element-docs/blob/master/ZEle%20config/%E6%A0%87%E5%87%86%20field/formField/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95field.md) 注入并替换原有的录入组件
