### ISSUE TITLE
文档说明如何变更按钮风格

### ISSUE THREAD

**Issue by a30f49** [kequandian/zero-element-docs#7]
包括 按钮颜色大小 （高度与宽度)

**Comment by youyeke** [comment]
目前除了导航菜单, 其它的组件都是使用了 antd 的 UI 组件, 故实际上是对 antd 组件的覆盖.

按钮的基础颜色信息可以通过 [颜色风格定义](https://github.com/kequandian/zero-element-docs/tree/master/Zero%20Code%20Admin#%E9%A2%9C%E8%89%B2%E9%A3%8E%E6%A0%BC%E5%AE%9A%E4%B9%89) 来覆盖

有关其它的样式信息, 可在 `src/rewrite.less` 里面自行编写覆盖.
